# Generated by Django 3.2.18 on 2023-02-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createcamp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('camp_name', models.CharField(max_length=30)),
                ('event_name', models.CharField(max_length=30)),
                ('fund_goal', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('stdate', models.CharField(max_length=30)),
                ('enddate', models.CharField(max_length=30)),
                ('camp_status', models.CharField(max_length=30)),
                ('total_amt', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('emailid', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='userdonation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('cid', models.CharField(max_length=30)),
                ('cname', models.CharField(max_length=30)),
                ('hash_code', models.CharField(max_length=30)),
                ('amt_donate', models.CharField(max_length=30)),
                ('donated_on', models.CharField(max_length=30)),
            ],
        ),
    ]
