# Generated by Django 3.2.18 on 2023-02-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcamp',
            name='camp_status',
        ),
        migrations.RemoveField(
            model_name='createcamp',
            name='total_amt',
        ),
    ]
