# Generated by Django 3.2.18 on 2023-02-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0002_auto_20230226_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createcamp',
            old_name='camp_name',
            new_name='cname',
        ),
        migrations.RemoveField(
            model_name='createcamp',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='createcamp',
            name='stdate',
        ),
    ]
