# Generated by Django 3.2.18 on 2023-02-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0003_auto_20230226_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='cretecampaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campname', models.CharField(max_length=50)),
                ('eventname', models.CharField(max_length=50)),
                ('goalfund', models.CharField(max_length=10)),
                ('locn', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='createcamp',
        ),
    ]
