# Generated by Django 3.2.18 on 2023-02-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0004_auto_20230226_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cretecampaign',
        ),
    ]
