# Generated by Django 3.2.18 on 2023-02-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundapp', '0005_delete_cretecampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='cretecampaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campname', models.CharField(max_length=50)),
                ('eventname', models.CharField(max_length=50)),
                ('goalfund', models.CharField(max_length=10)),
                ('locn', models.CharField(max_length=50)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('camp_status', models.CharField(max_length=50)),
                ('camp_totalamt', models.CharField(max_length=50)),
            ],
        ),
    ]
